version: '3'  
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: 'R#7mL*o2Pz!9'
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 10s  
  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - SQL_PASSWORD=R#7mL*o2Pz!9
      - SQL_HOST=db
      - SQL_USER=postgres
      - SQL_NAME=postgres
      - MY_TOKEN_SECRET=miSecreto
      - PORT=3000
    volumes:
      - ./server:/server
    ports:
      - "3000:3000"
    healthcheck:
      test: wget --tries=1 --spider http://localhost:3000/api/login/logout || exit 1
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
        restart: true
  web:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      VITE_API_HOST: localhost:3000
    volumes:
      - ./client:/client
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
        restart: true
volumes:
  demo_app: