version: '3'  
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 10s  